### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Natansh2005**

### CODE REVIEW

**Comment by Mohammed-Shoaib** [comment]
Hey @Natansh2005,

Thank you for submitting the first pull request! 🙌

However, I am not sure what change was being done. I prefer the heading as it is meaning `# Coding Problems` instead of the updated `<<Coding Problems>>`.

Could you please provide more information?

Thanks,
Mohammed Shoaib 🦄

**Comment by Natansh2005** [comment]
it will appear professional code that's why sir, I will change this # Coding problem into this <<Coding Problems>>.

**Comment by Mohammed-Shoaib** [comment]
Thank you so much for providing feedback and suggestion! :sparkles: 

I appreciate your contribution but I much prefer `# Coding Problems`. You generally want to keep the name of the repository as the heading of your README file!

I am open to further contributions in the future. Please do let me know if you find any errors or incorrect solutions :relaxed: 

Thank you and have a nice day ahead! :unicorn:

**Comment by Natansh2005** [comment]
Ok
it will become better code bro that' that's why I will change

**Review by Siddhant-K-code — COMMENTED** [review]
Unnecessary PR

**Comment by Mohammed-Shoaib** [comment]
It's alright, I appreciate people contributing to this repo! :heart:

**Comment by Natansh2005** [comment]
ok Sir, But it's end Please don't disturb me by sending mail or Commenting
on Github
And, If you think I am insulting you.
Then it's your mentality.
And, for your mentality, I regret / disappointed for THIS MAIL..
SORRY Again.

**Comment by Siddhant-K-code** [comment]
> Please don't disturb me by sending mail or Commenting

You Can Unsubscribe to it, I was just pointing out the thing.

So, No Mail From Now

**Pull request closed without merging**
